### ISSUE TITLE
Subspec framework names

### ISSUE THREAD

**Issue by jhersh** [neonichu/Rome#10]
My `Podfile` includes a few subspecs.

```
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: 
can't open input file: /Users/jh/Dev/MUDRammer/src/build/Release-iphoneos/ARAnalytics/CoreIOS.framework/ARAnalytics/CoreIOS (No such file or directory)
```

Maybe this should be named `ARAnalytics-CoreIOS.framework` rather than creating a subfolder?

```bash
Errno::ENOENT - No such file or directory @ sys_fail2 - (/Users/jh/Dev/MUDRammer/src/build/ARAnalytics/CoreIOS, /Users/jh/Dev/MUDRammer/src/build/Release-iphoneos/ARAnalytics/CoreIOS.framework/ARAnalytics/CoreIOS)
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:527:in `rename'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:527:in `block in mv'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:1586:in `fu_each_src_dest0'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/fileutils.rb:516:in `mv'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:27:in `block (4 levels) in <top (required)>'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:22:in `each'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:22:in `block (3 levels) in <top (required)>'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:17:in `each'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:17:in `block (2 levels) in <top (required)>'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:15:in `chdir'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:15:in `block in <top (required)>'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/hooks_manager.rb:117:in `call'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/user_interface.rb:140:in `message'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/hooks_manager.rb:109:in `each'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/user_interface.rb:140:in `message'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/hooks_manager.rb:108:in `run'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:445:in `run_plugins_post_install_hooks'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:437:in `perform_post_install_actions'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/installer.rb:111:in `install!'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-keys-1.4.0/lib/plugin.rb:94:in `install!'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/lib/cocoapods/command.rb:48:in `run'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/gems/cocoapods-0.38.0.beta.2/bin/pod:44:in `<top (required)>'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/bin/pod:23:in `load'
/Users/jh/Dev/MUDRammer/vendor/bundle/ruby/2.2.0/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
Fixed by #13
