### ISSUE TITLE
Errno::ENOENT

### ISSUE THREAD

**Issue by drewcrawford** [neonichu/Rome#22]
When I build Mixpanel via Rome, I get `ENOENT`.

The project in this directory is just a freshly-created Xcode template project.

### Versions

Xcode Version 6.4 (6E35b)
OSX 10.10.4 (14E46)

### Stack

```
   CocoaPods : 0.38.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5d6927ee9e98868c4e7919eca94440e7648d5f4e
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-rome    : 0.1.0
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '8.2'
use_frameworks!

plugin 'cocoapods-rome'

pod 'Mixpanel'
```

### Error

```
Errno::ENOENT - No such file or directory - /Users/drew/Code/Mixpanel-rome/build/Mixpanel/Mixpanel
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `stat'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1568:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1550:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:508:in `mv'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:27:in `block (4 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:22:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:22:in `block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:17:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:17:in `block (2 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:15:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-rome-0.1.0/lib/cocoapods-rome/post_install.rb:15:in `block in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/hooks_manager.rb:117:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:448:in `run_plugins_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:440:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/installer.rb:111:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
This was possibly caused by #10, but there's also now slightly better logging for the case where lipo fails. In any case, this works now with the new 0.2.0 version that was just released.
