### ISSUE TITLE
Add support for local specs (:path in Podfile)

### ISSUE THREAD

**Issue by stepanhruda** [neonichu/Rome#24]
I have a Podfile that references local podspecs via _:path_, which I think is pretty common in a monorepo. After building all frameworks, I get

```
Built 86 frameworks
[!] Attempt to read non existent folder `{path to repo}/Pods/{local pod name}`.

/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:48:in `read_file_system'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:31:in `files'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:117:in `relative_glob'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:79:in `glob'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:314:in `expanded_paths'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:285:in `paths_for_attribute'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:187:in `vendored_libraries'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-rome-0.2.0/lib/cocoapods-rome/post_install.rb:60:in `block (3 levels) in <top (required)>'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-rome-0.2.0/lib/cocoapods-rome/post_install.rb:57:in `each'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-rome-0.2.0/lib/cocoapods-rome/post_install.rb:57:in `block (2 levels) in <top (required)>'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-rome-0.2.0/lib/cocoapods-rome/post_install.rb:56:in `each'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-rome-0.2.0/lib/cocoapods-rome/post_install.rb:56:in `block in <top (required)>'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:117:in `call'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:109:in `each'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:108:in `run'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:453:in `run_plugins_post_install_hooks'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:444:in `perform_post_install_actions'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:112:in `install!'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/bin/pod:23:in `load'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/bin/pod:23:in `<main>'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/stepanhruda/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment]
@stepanhruda can you please share the output of `pod install --verbose`? This isn't really enough info to debug with :/

**Comment by stepanhruda** [comment]
Updated the output above
