### ISSUE TITLE
NoMethodError - with Cocoapods-1.0.0.beta.6

### ISSUE THREAD

**Issue by petripartanen** [neonichu/Rome#38]
――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
Tried installing Swiftline

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.0.beta.6
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 64ccd734fe09c4d28bfabeb9393735fd5e05900f
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-rome        : 0.4.2
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.2
cocoapods-try         : 1.0.0.beta.3
```

### Podfile

```ruby
platform :osx, '10.11'

plugin 'cocoapods-rome'

pod 'Swiftline'
```

### Error

```
NoMethodError - undefined method `integrate_targets=' for #<Pod::Config:0x007fe2d1484598>
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-rome-0.4.2/lib/cocoapods-rome/pre_install.rb:3:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/hooks_manager.rb:111:in `block (3 levels) in run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:144:in `message'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/hooks_manager.rb:101:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:144:in `message'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/hooks_manager.rb:100:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:443:in `run_plugins_pre_install_hooks'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:136:in `block in prepare'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:144:in `message'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:131:in `prepare'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:113:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.0.beta.6/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by segiddins** [comment]
Rome is not yet compatible with CocoaPods 1.0, iirc.

**Comment by petripartanen** [comment]
alright, thanks for the reply

**Comment by neonichu** [comment]
Yep, I got a branch, will push it in the next few days. The gem will probably not be updated until 1.0 final, though.

**Comment by neonichu** [comment]
See #39
