### ISSUE TITLE
cato causes rome to crash

### ISSUE THREAD

**Issue by kylef** [neonichu/Rome#7]
```
$ cat test.swift
#!/usr/bin/env cato

import URITemplate

let template = URITemplate(template: "test")
println("\(template)")
```

```
$ ./test.swift
Analyzing dependencies
Downloading dependencies
Installing URITemplate (1.1.1)
Generating Pods project
Building frameworks
```

### Command

```
/Users/kyle/gems/bin/pod install --project-directory=/Users/kyle/.📦/test --no-repo-update --no-integrate
```

### Stack

```
   CocoaPods : 0.36.3
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.2 (14C109)
       Xcode : 6.2 (6C131e)
         Git : git version 1.9.5 (Apple Git-50.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : atest -  @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               b -  @ 890a50800684d5b90a9a77e6bf12d7568c8f8424
               foo -  @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               master - https://github.com/CocoaPods/Specs.git @ 979208d98333eeec177a1dfdd645e7dc0cc6c8fc
```

### Plugins

```
cocoapods-deintegrate  : 0.2.1
cocoapods-dependencies : 0.4.0
cocoapods-plugins      : 0.4.1
cocoapods-rome         : 0.0.3
cocoapods-trunk        : 0.3.1
cocoapods-try          : 0.4.3
```

### Podfile

```ruby
platform :osx, '10.10'
plugin 'cocoapods-rome'
use_frameworks!
pod "URITemplate"
```

### Error

```
NoMethodError - undefined method `map' for "-project Pods.xcodeproj -scheme Pods -configuration Release":String
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/executable.rb:57:in `execute_command'
/Users/kyle/gems/gems/cocoapods-rome-0.0.3/lib/cocoapods-rome/post_install.rb:14:in `block (3 levels) in <top (required)>'
/Users/kyle/gems/gems/cocoapods-rome-0.0.3/lib/cocoapods-rome/post_install.rb:13:in `each'
/Users/kyle/gems/gems/cocoapods-rome-0.0.3/lib/cocoapods-rome/post_install.rb:13:in `block (2 levels) in <top (required)>'
/Users/kyle/gems/gems/cocoapods-rome-0.0.3/lib/cocoapods-rome/post_install.rb:11:in `chdir'
/Users/kyle/gems/gems/cocoapods-rome-0.0.3/lib/cocoapods-rome/post_install.rb:11:in `block in <top (required)>'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/hooks_manager.rb:115:in `call'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/hooks_manager.rb:115:in `block (3 levels) in run'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:110:in `message'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/hooks_manager.rb:109:in `block (2 levels) in run'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/hooks_manager.rb:107:in `each'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/hooks_manager.rb:107:in `block in run'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/user_interface.rb:110:in `message'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/hooks_manager.rb:106:in `run'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:402:in `run_plugins_post_install_hooks'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:394:in `perform_post_install_actions'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/installer.rb:98:in `install!'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/command/project.rb:101:in `run'
/Users/kyle/gems/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/kyle/gems/gems/cocoapods-0.36.3/lib/cocoapods/command.rb:46:in `run'
/Users/kyle/gems/gems/cocoapods-0.36.3/bin/pod:44:in `<top (required)>'
/Users/kyle/gems/bin/pod:23:in `load'
/Users/kyle/gems/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment]
The issue here is that Rome 0.0.3 is incompatible with CP 0.36.3 => `gem install cocoapods-rome` :tada:
